changed date format
Karolis11/SEappIII pull request #45
Opened 2022-11-01 13:15 UTC by Karolis11

2022-11-03 11:17 UTC, TisIDom requested changes
All the changes needed are mentioned in the comments.

2022-11-03 11:17 UTC, TisIDom commented on roommate-app/Controllers/Login/LoginController.cs
> +        _file = file;
Data should be read from the database using UserService and not from a file.

2022-11-03 11:17 UTC, TisIDom commented on roommate-app-testing.UnitTests/UnitTest1.cs
> +}
This whole file will have to be changed once LoginController reads from the database.

2022-11-06 13:57 UTC, dominykase approved these changes
Tests look good, but not sure if Login and Registration test should be in the same file. Letting it pass for now.

2022-11-07 12:19 UTC, TisIDom approved these changes

2022-11-07 12:34 UTC, merged